version: "3.9"
services:
  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: tickets
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - dbdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Console
    volumes:
      - miniodata:/data

  app:
    build: .
    depends_on:
      - db
      - minio
    environment:
      APP_URL: http://localhost:3000
      AUTH_SECRET: replace-with-a-long-random-string
      DATABASE_URL: postgresql://postgres:postgres@db:5432/tickets?schema=public
      RESEND_API_KEY: replace-me
      ADMIN_EMAIL: admin@example.com
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_SSL: "false"
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: ticket-attachments
      AUTO_CLOSE_DAYS: 14
    ports:
      - "3000:3000"

  # Optional: run the auto-close job hourly
  autoclose:
    build: .
    depends_on:
      - db
    command: sh -c "while true; do node scripts/auto-close-resolved.mjs; sleep 3600; done"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/tickets?schema=public
      RESEND_API_KEY: replace-me
      APP_URL: http://localhost:3000
      AUTO_CLOSE_DAYS: 14

volumes:
  dbdata:
  miniodata:
